### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by marcostoduto** [JEToP/jetop_credentials_backend#1]
Implement tables from [definition scheme](https://github.com/JEToP/jetop_credentials_backend/wiki/Database-Definition) following [LB4 guidelines and tutorials](https://loopback.io/doc/en/lb4/todo-tutorial.html)

- [x] **User**
   - [x] Model
   - [x] Repository
   - [x] Controller
- [x] **Service**
   - [x] Model
   - [x] Repository
   - [x] Controller
- [x] **Credential**
   - [x] Model
   - [x] Repository
   - [x] Controller
- [x] **History**
   - [x] Model
   - [x] Repository
   - [x] Controller
-----

- [ ] Setup automigrate
- [ ] Setup autoupdate

**Comment by Thanzex** [comment]
@marcostoduto Per impostare le relazioni aspettiamo le PR di tutti i modelli ?

**Comment by powext** [comment]
> @marcostoduto Per impostare le relazioni aspettiamo le PR di tutti i modelli ?

What's this pizza mandolino language?

**Comment by marcostoduto** [comment]
> @marcostoduto Per impostare le relazioni aspettiamo le PR di tutti i modelli ?

Yes I would says so
